
package mnu.service.impl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InvalidIdException", targetNamespace = "http://impl.service.mnu/")
public class InvalidIdException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private EmployeeServiceFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InvalidIdException(String message, EmployeeServiceFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public InvalidIdException(String message, EmployeeServiceFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: mnu.service.impl.EmployeeServiceFault
     */
    public EmployeeServiceFault getFaultInfo() {
        return faultInfo;
    }

}
